PULL_REQUEST_TEMPLATE.md

PR/PD-39 feat:Pull_Request_Template

---

.eslintrc.js
.prettierrc.js
package-lock.json
package.json

<br/>
<br/>
노션 컨벤션을 참고하여 eslint와 prettier 초기 설정을 완료하였습니다
<br/>
<br/>
<br/>
<br/>
3. Comment 입력(선택사항) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.
</div>
<br/>
```text
```
</div>
<br/>
<br/>

PR/PD-40 feat: eslint, prettier 초기 설정

---

.github/PULL_REQUEST_TEMPLATE.md

<br/>
<br/>
- backlog 등 작업 관리를 Linear 에서 진행하기로 해서, 이슈번호를 적는 "🔥 Issue" 항목은 제거했습니다.
- 이전 프로젝트가 삭제됨에 따라, 해당 프로젝트에서 사용한 template 속 이미지는 불러와지지 않았습니다. 
- 다들 리뷰남기는 방법이 충분히 공유되었으니, 리뷰 남기는 방법에 대한 참고 이미지는 삭제했습니다. 👍
<br/>
<br/>
<br/>
<br/>
3. Comment 입력(선택사항) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.
</div>
<br/>
```text
```
</div>
<br/>
<br/>

PR/PD-39: PR Template 수정

---

src/utils/auto-color-manager.js
src/utils/index.js

- [feat: auto-color 기능을 추가하였습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/a86450600070ca69b09b6a350b3bccb236129823)
- auto-color 기능은 숫자로 된 id 값 또는 문자로 된 text 값에 따라 색상 테마를 부여하는 기능입니다.
- text 는 유니코드(숫자)로 변환하는 함수를 이용하였습니다.
- 이 기능을 사용하면 "고구마" 같은 text나 "1392125"과 같은 id에 {base, light, weight} 와 같은 색상 테마를 사용하여 배경, 폰트 색상을 부여할 수 있습니다.
<br/>
<br/>
<br/>
<br/>
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.
<br/>
```text
```
<br/>
<br/>

PR/PD-54 auto-color 기능을 추가하였습니다.

---

package-lock.json
package.json

- [config: react-icons 의존성 추가](https://github.com/PurpleDynamics/PEA_Project/commit/330af8cad3df98f1255ed186a6363ad0cb30c2be)
- 아이콘 라이브러리 react-icons 의존성 추가했습니다.
<br/>
<br/>
<br/>
<br/>
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.
<br/>
```text
```
<br/>
<br/>

PR/PD-64: react-icons 의존성 추가했습니다.

---

src/components/commons/icon.jsx
src/components/commons/index.js
src/components/commons/responsive-icon.jsx

- [design: 공용컴포넌트 Icon 생성](https://github.com/PurpleDynamics/PEA_Project/commit/8649472b879b30f1bd2686bed0e815021802baee)
- Icon 컴포넌트 생성했습니다.
- 외부에서 주입받은 icon component 에, 호버 시 scale 확대 효과를 적용합니다.
- [move: 컴포넌트명 변경 (Icon -> ResponsiveIcon)](https://github.com/PurpleDynamics/PEA_Project/commit/e60d180eb01211d3e5aa549ef9e9434f9d5515ab)
- 클릭 이벤트 등이 가능하도록, `rest` 이름으로 추가적인 속성 전달했습니다.
- 기존 react-icon 컴포넌트와 다르게 사용자의 행동에 반응한다는 의미가 명확해지도록 "ResponsiveIcon" 으로 컴포넌트 이름을 변경했습니다.
<br/>
<br/>
- _코드_
```js
// https://react-icons.github.io/react-icons/icons/bs/ 에서 적절한 아이콘 찾아서 imort!!
import { BsBagXFill } from "react-icons/bs"; 
return (
// 아이콘 컴포넌트와 size, color 등 전달 
<ResponsiveIcon
icon={BsBagXFill}
size={FONT_SIZE.xl}
color={COLOR.PALETTE.magenta.light}
/>
);
```
- _출력물_
------
<br/>
<br/>
<br/>
<br/> …

PR/PD-65: 공용컴포넌트 "ResponsiveIcon" 작성했습니다.

---

src/components/commons/button.jsx
src/components/commons/index.js
src/libs/styled-components/global-styles.jsx

https://github.com/PurpleDynamics/PEA_Project/assets/50646145/feb196c6-88f4-4280-be10-6d1f26b1fc39
--------
</div>
- [design: 공용컴포넌트 Button 생성](https://github.com/PurpleDynamics/PEA_Project/commit/2efd672016b0e7226e8b84151003d3ed09ff791a)
- 호버, 눌림에 대한 효과가 적용된 버튼 컴포넌트 입니다.
- 색상 조합이 이미 결정되어 있습니다. 'palette' 이름으로 색상 조합과 관련된 key 값을 입력하면, normal, hover, active 시 색상이 자동으로 지정됩니다.
- 버튼에 아이콘이 삽입되어야 한다면, react-icons 라이브러리 통해서 icon 컴포넌트 전달해주시면 됩니다.
- 그 외, `<button>` 태그와 사용법은 동일합니다.
<br/>
<br/>
- _코드_
```js
<Button>디폴트</Button>
```
- _출력물_
------
- _코드_
```js
<Button palette="orange">오렌지</Button>
```
- _출력물_
------
- _코드_
```js
import { BsArrowUpLeftCircleFill } from "react-icons/bs";
.
.
.
<Button palette="cyan" icon={BsArrowUpLeftCircleFill}>아이콘</Button>
```
- _출력물_
<br/>
<br/> …

PR/PD-36: 공용컴포넌트 "Button" 작성했습니다.

---

package-lock.json
package.json
src/components/commons/index.js
src/components/commons/input.jsx

- [config: react-hook-form 의존성 추가](https://github.com/PurpleDynamics/PEA_Project/commit/761481d16aa8eebf9bb50d09b8cb7552bffaa76c)
- react-hook-form 라이브러리 사용을 전제합니다.
- 미리 의존성 추가했습니다.
- [design: 공용컴포넌트 Input 생성](https://github.com/PurpleDynamics/PEA_Project/commit/cfad23928e9082f031ca4af956c6bab83d474f27)
- 시용자 입력에 대하여 유효성 검사 및 검사 실패 시 에러메시지가 출력되는 컴포넌트입니다.
- react-hook-form 라이브러리 사용을 전제합니다.
- 'unitText' 값이 전달될 시, 입력값이 우측 정렬되어 출력되며, 해당 단위가 출력됩니다.
- 'buttonText' 값이 전달될 시, 해당 컴포넌트 내부 우측에 해당 텍스트 내용이 담긴, button 이 생성됩니다.
- 'disabled' 상태 시, 입력을 할 수 없습니다.
<br/>
<br/>
- _코드_
```js
const {
register,
handleSubmit,
formState: { errors },
} = useForm({ mode: "onChange" });
return (
.
.
.
<Input
titleText="Email"
validate={{
required: "필수 응답 항목입니다.",
pattern: {
value: /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i, …
```

PR/PD-43: 공용 컴포넌트 "Input" 작성했습니다.

---

src/components/commons/category-toggle.jsx
src/components/commons/index.js
src/components/index.js

- [fix: 충돌 미해결 merge 된 건에 대하여 해결](https://github.com/PurpleDynamics/PEA_Project/commit/88012052a0c6cc857dcf99a0a295d0df5e5073a8)
- `components > common > index.js` 오타가 있었습니다. 수정했습니다.
- 추가로 CategoryToggle `common` 폴더로 이동시켰습니다.
<br/>
<br/>
<br/>
<br/>
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.
<br/>
```text
```
<br/>
<br/>

PR: 충돌 미해결 merge 된 건에 대하여 해결했습니다.

---

src/libs/react-router-dom/admin-router.jsx

- [fix: useEffect 추가](https://github.com/PurpleDynamics/PEA_Project/commit/4f322570d54e2cbdbdd449c53925c5cd2b90a933)
- admin-router에서 useEffect 가 import 되어 있지 않은것을 발견했습니다.
- 현재 main 에서 오류가 발생합니다
- (다 확인하고 올렸는데 이런 이슈가!!)
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR/PD-41: useEffect 추가 ( 빠른 merge 부탁드립니다. 급함!!!)

---

src/components/commons/button.jsx

- [refactor: 버튼 너비를 외부에서 주입하도록 변경](https://github.com/PurpleDynamics/PEA_Project/commit/b6a35cd702b6377e6ddc530ffb388ec687a01973)
- pr 제목과 내용이 같습니다.
- 기존처럼 사용해도 문제 없도록 작성했습니다.
- _코드_
```js
<Button width="100%">full</Button>
```
- _출력_
<br/>
<br/>
<br/>
<br/>
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.
<br/>
```text
```
<br/>
<br/>

PR/PD-36: 버튼 너비를 외부에서 주입하도록 변경

---

package-lock.json
src/components/commons/button.jsx
src/components/commons/input.jsx

- [feat: 버튼 호버 시, cursor 변경](https://github.com/PurpleDynamics/PEA_Project/commit/5c5a4c599fbaf3b7a7d5d74354271e95ee112240)
- 버튼 호버 시, 커서 변경했습니다.
- [chore: Input 내부 버튼 너비 고정 & color 변경](https://github.com/PurpleDynamics/PEA_Project/commit/11834ac76801959562018fd76a77c3af4d72c35c)
- 버튼 너비를 6rem 으로 변경했습니다.
- 버튼 색상 변경했습니다.
- [fix: react-icons 의존성 재설정](https://github.com/PurpleDynamics/PEA_Project/commit/44589e0a290ca49785c24816ff5a38d596fd8db2)
- pull 받았을 때, react-icons 과 관련하여 package.lock.json 이 변경되는 이슈가 있었습니다. 수정했습니다.
- [refactor: titleText 로 input을 구분했던 로직을 별도의 props로 분리](https://github.com/PurpleDynamics/PEA_Project/commit/9c9cf7eb6dcf123a55225f35bea07cd2bff44f56)
- 기존에는 `titleText` 값으로로 react-hook-form 유효성 검사 key를 등록했습니다.
- 디스플레이에 출력되어야할 `titleText` 와 `Input` 에 고유한 key 값을 분리하도록 수정했습니다. …

PR: input, button 등 공용컴포넌트 상세 수정한 사항입니다.

---

src/components/commons/compression-container.jsx

- [design: compression-container 생성](https://github.com/PurpleDynamics/PEA_Project/commit/a6a4f7792d7fb1f4024bbfa4cfa6527b832fd247)
- 상-하, 좌-우 의 값을 입력받아 여백을 생성하는 컴포넌트입니다.
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR/PD-61: compression-container 생성

---

src/components/commons/banner.jsx
src/components/commons/index.js

- [design: 공용컴포넌트 banner 작업완료](https://github.com/PurpleDynamics/PEA_Project/commit/c74228b0803c73a63d5c5d8d59348659eb081034)
- 변경점이 많이잡혀서 다시pr올리는것이니 혹시 내용보시려면 closed된 pr확인해주세요~
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR:PD-53: 공용컴포넌트 banner작업했습니다.

---

src/components/commons/input.jsx
src/constants/index.js
src/constants/validate-message.js
src/pages/signup-page.jsx

[feat : input 에 cursor pointer 추가](https://github.com/PurpleDynamics/PEA_Project/commit/746274e0ad5186f6ad98cd1cadd651ad8a39935a)
(해당 수정사항은 input 브랜치에서 해야하는게 맞지만 협의하에 제가 진행하였습니다^^.. 양해부탁드립니다.)
- input 창 안에 buttonText(중복확인) 버튼 호버시 cursor : pointer 추가
[design : signup-page 생성](https://github.com/PurpleDynamics/PEA_Project/commit/49d7cd4d43333c7ecf829b1a46df68f554087b42)
- 이메일 , 비밀번호, 닉네임 작성부분에는 해당부분에 맞는 정규 표현식 코드를 사용하였습니다.
(이메일: 이메일 형식 / 비밀번호: 8글자이상 / 닉네임: 특수문자금지)
<video  src= "https://github.com/PurpleDynamics/PEA_Project/assets/142880051/123aadf2-fb44-44af-a9b3-1cf707dbed85
"></video>
- '가입하기' 버튼 클릭시 signin-page로 넘어갑니다.
- 닉네임 입력창은 autoComplete 이 불필요할것같아 off로 설정해 두었습니다.
[refactor: 반응형 웹사이트로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/69d5ca3c82b31f77b969c87ddf826ff0322 …

PR/PD-67: signup-page 작업했습니다.

---

src/components/commons/compression-container.jsx
src/components/commons/index.js

- [fix: 중복된 컴포넌트 삭제](https://github.com/PurpleDynamics/PEA_Project/commit/42e0df9e957da7bb048fada5f61e168cba7cfd20) 
- 버튼 등 컴포넌트 import,export 가 중복되어 작성되어있었습니다. 수정합니다.
- [chore: CompressionContainer 철자 오타 수정](https://github.com/PurpleDynamics/PEA_Project/commit/8f31169605c9ef63e4a1bdb5d92ee2d7b4be0114)
- CompressionContainer 철자 수정합니다. `CompressoionContainer` => `CompressionContainer`
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 …

PR: `src>components>commons` barrel-file 중 중복된 컴포넌트 삭제합니다.

---

src/pages/signin-page.jsx

[feat: signin page 생성](https://github.com/PurpleDynamics/PEA_Project/commit/8d8017942fa6ace23f8768cf9fb3497ac822b2dd)
- signin-page 생성했습니다.
- 회원가입과 마찬가지로 이메일과 비밀번호 창에는 ```constants```폴더 안에 유효성 검사 메세지 ```VAILDAITION``` 을 넣었습니다.
- 로그인 버튼은 이메일과 비밀번호 형식에 맞으면 자동으로 활성화되도록 했습니다.
<video src="https://github.com/PurpleDynamics/PEA_Project/assets/142880051/68d13629-d819-4a71-ae06-f105841fca10"></video>
- signup 페이지와 같이 화면이 어느정도 크기 까지 작아지면 (```BREAK_POINT.md```) 아래 화면과 같이 반응합니다.
<br/>
<br/>
<br/>
```text …
```

PR/PD-48: login-page 생성했습니다.

---

src/components/commons/recent-product-list.jsx
src/components/commons/side-chat-button.jsx

- 최근 본 상품 UI 변경하였습니다.
- backgroun-color: ${COLOR.COMMON[1000]}로 지정했습니다.
- SideChatButton 컴포넌트와 관련하여 chatting Icon 사이즈 변경 및 display 방식 설정했습니다.
- title 사이즈 수정하였습니다.
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR/PD-68: RecentProductList 컴포넌트 background-color 지정 및 요소 Re-sizing 변경

---

src/index.js

- RouterProvider 삭제된 모듈 복원했습니다.
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: RouterProvider 삭제된 모듈 복원

---

src/components/commons/icon-and-text.jsx

- [chore: appendUnit삭제 & props변경](https://github.com/PurpleDynamics/PEA_Project/commit/7d6e369c43f3affc5710d5cc0ce7704c7118a655)
- 1. appendUnit() 부분을 삭제했습니다.
- 2. props를 변경했습니다. 
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: icon-and-text컴포넌트 변경사항있어서 수정했습니다.

---

src/components/overlay/index.js
src/components/overlay/modal.jsx

BaseButton 기능이없는경우 close가 실행이안되는부분이있어 필수로 넣는것이아닌 Button 기능은 onclose(base)+@가 되도록 했습니다
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: modal-common 배경및 button 기본 기능변경

---

src/components/commons/compression-container.jsx
src/components/commons/compression-wrapper.jsx
src/components/commons/index.js
src/components/product-list/eight-product-grid.jsx
src/components/product-list/promotion-banner.jsx
src/pages/register-product-page.jsx

- [refactor: 기본값 수정](https://github.com/PurpleDynamics/PEA_Project/commit/347f51019564c6f60e38a82e53590eee04769328)
- 좌우여백 `lr` 에 대한 속성, 상하여백에 대한 속성 `tb` 기본값을 0 으로 수정했습니다.
- 수정 이유는 다음과 같습니다.
- 기존 코드 상에, `tb` 와 `lr` 이 모두 기본값이 `20rem` 으로 설정되어 있었습니다.
- 좌우 여백만 필요한 경우에도 `tb` 값을 부여해야 하는 어려움이 있었습니다.
- [refactor: compression-container 컴포넌트 이름 수정](https://github.com/PurpleDynamics/PEA_Project/commit/948c57001e21b2e88d6136c02cded4d7fb1f6d19)
- @KR-HeoJU 24.02.14 회의 내용에 따라 컴포넌트 이름에 대한 컨벤션이 정의 되었습니다. 
```js
// ~~Cotainer 는 
// 직속(?) 자식이 하나 있는 경우에만 사용합니다.
<Container>
<div>
<button>버튼</button>
<button>버튼</button>
</div>
</Container>
```
```js
// ~~Wrapper 는 
// 직속(?) 자식이 둘 이상 있는 경우에 사용합니다.
<Wrapper>
<div>
<button>버튼</button>
<button>버튼</button>
</div>
<div>
<button>버튼</button>
<button>버튼</button> …
```

PR/PD-79: CompressionContainer 컴포넌트 이름 변경 & 기본값 수정

---

src/components/overlay/modal.jsx

<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR/PD-80: 모달 컴포넌트 리펙토링 진행했습니다.

---

src/components/commons/search-bar.jsx
src/components/commons/side-chat-button.jsx
src/components/layouts/header.jsx
src/components/overlay/chatting/chat-room-list.jsx
src/components/overlay/chatting/chat.jsx
src/components/overlay/chatting/chatting-overlay.jsx
src/components/overlay/chatting/index.js

오류로 인해서 다시 PR 올립니다
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR/PD-56: design/chatting-overlay-common 다시 PR 올립니다.

---

src/components/overlay/modal.jsx

- [design: border 추가](https://github.com/PurpleDynamics/PEA_Project/commit/294400470da594e79abf7346a269d8d4c8a3a108)
- 경계선 추가했습니다.
<br/>
<br/>
<br/>
- __이전 PR 에서 미흡했던 작업 내용 보안 작성합니다.__
1. 기본 (상위의 이미지처럼 출력됩니다.)
```js
import { Modal } from "../components/overlay";
import { useOverlay } from "../hooks/use-overlay";
const { onOpenOverlay } = useOverlay();
const onClickOpenModal = () => {
onOpenOverlay({
overlayComponent: Modal,
noticeText: "안녕하세요.",
});
};
```
---------
2.  모달 버튼의 색상을 변경하여 주의 상태를 표시 할 수 있습니다.  
- success 
_상위 코드와 동일합니다. (기본값이 "success")_
- alert
```js
import { Modal } from "../components/overlay";
import { useOverlay } from "../hooks/use-overlay";
const { onOpenOverlay } = useOverlay();
const onClickOpenModal = () => {
onOpenOverlay({
overlayComponent: Modal,
modalState: …
```

PR/PD-80: 모달 컴포넌트 border 추가 등 작업했습니다.

---

src/components/commons/index.js
src/components/commons/text-spacer.jsx

- [design: text-spacer 생성했습니다](https://github.com/PurpleDynamics/PEA_Project/commit/a1ecfc81d38e826c21d4c36f7c8a7c83f8cda600)
- 글자 사이에 공백을 주는 컴포넌트입니다.
- 기본값은 1 입니다.
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: text-spacer 생성했습니다

---

package-lock.json
package.json
src/constants/index.js
src/constants/query-key.js
src/index.js
src/libs/axios/base/products.js
src/libs/react-query/index.js
src/libs/react-query/products.js

- [config: react-query 의존성 추가 및 Provider 설정](https://github.com/PurpleDynamics/PEA_Project/pull/54/commits/a6aa937c20d15ef7ba27bbc2f83b8e756211e82a)
- react-query 라이브러리 설치했습니다.
- `index.js` 에 `queryClient` 객체 작성하여 Provider 컴포넌트에 제공했습니다.
- [feat: product-list 캐싱 함수 작성] (https://github.com/PurpleDynamics/PEA_Project/pull/54/commits/55a109cdb2aafea4d57b0b96f799b0fd5e48c8e2)
- [feat: 카테고리에 의한 상품 리스트 데이터 캐싱 함수 작성](https://github.com/PurpleDynamics/PEA_Project/pull/54/commits/3dcf5446b0402424342358668a83c3a11b31c1a6)
- [feat: 단일 상품 조회 데이터 캐싱 함수 작성](https://github.com/PurpleDynamics/PEA_Project/pull/54/commits/6c7da0346b4bef7f99691320f1dbc3ca6e669f35)
- 상품 조회와 관련한 데이터를 캐싱/접근 하는 함수 작성했습니다.
- 다음과 같이 사용할 수 있습니다.
```js
const { data, isLoading, isError } = useGetProductListByPaymentMethod({ userId: …
```

PR/PD-82: react-query 의존성 추가 및 설정, 상품 데이터 캐싱 함수 작성했습니다.

---

src/utils/index.js

- [remove: 삭제된 chart-calculator.js index에서 삭제](https://github.com/PurpleDynamics/PEA_Project/commit/afa61857febcb5b487e55661a1a38f903931d29c)
- 삭제된 chart-calculator.js index에서 삭제하지 않은채로 merge해서 급하게 fix했습니다.
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: 삭제된 chart-calculator.js index에서 삭제

---

src/components/commons/center-box.jsx
src/components/commons/index.js

- [design: center-box 컴포넌트 생성](https://github.com/PurpleDynamics/PEA_Project/commit/693d2c4f71930f4e98adb4ab21c0c8a2216a9772)
- 전체 스크린 크기가 아무리 크더라도, 내부 컨텐츠 요소의 최대 너비는 115.2rem 을 유지하도록 합니다.
- 배경색(bgColor) 을 지정할 경우, 전체 스크린 너비만큼의 영역이 지정된 색으로 채워집니다.
</div>
<br/>
<br/>
1. bgColor 미지정 
- _코드_
```js
<CenterBox>
<div
style={{
backgroundColor: "yellow",
height: "10rem",
display: "flex",
justifyContent: "center",
alignItems: "center",
}}
>
자식컴포넌트1
</div>
</CenterBox>
```
- _스크린샷_
-------------
<br/>
<br/>
2. bgColor 지정 
- _코드_
```js
<CenterBox bgColor="red">
<div
style={{
backgroundColor: "yellow",
height: "10rem",
display: "flex",
justifyContent: "center",
alignItems: "center",
}}
>
자식컴포넌트1
</div>
</CenterBox>
```
- _스크린샷_
<br/>
<br/>
-   [x] PR 제목 …

PR/PD-83: 공용컴포넌트 "CenterBox" 작성했습니다.

---

src/components/layouts/header.jsx
src/components/product-list/promotion-banner.jsx
src/pages/product-list-page.jsx

- [fix: publish-main searchbar 위치조정, header 크기 115.2rem으로 조정](https://github.com/PurpleDynamics/PEA_Project/commit/110e53d4bcde0b64b8563559aa53ce59e4167d0d)
- search bar 위치를 조정했습니다.
- header 의 search bar 의 padding-left 값이 적용되지 않은 걸 확인하여 padding-left 14rem 만큼 이동하였습니다.
- [fix: compression wrapper 제거](https://github.com/PurpleDynamics/PEA_Project/pull/60/commits/e8968b46171b3e0a154eb14364bfc5826042d0df)
-  compression wrapper 제거 후 가운데 정렬했습니다.
- header 와 footer의 길이가 125rem으로 설정되있는걸 확인하고 115.2rem으로 재 조정하였습니다.
- [fix: promotion-banner 버튼 이벤트 추가 및 product 더보기 추가](https://github.com/PurpleDynamics/PEA_Project/pull/60/commits/c03bbdc21df7667e660dfe70dc03d6448821c402)
- promotion banner 및 더보기 버튼 클릭 시 navigate에 "중고거래", "무료나눔"을 가져갈 수 있도록 설정했습니다.
- useLocation을 사용하여 변수명.type 으로 불러오면됩니다
- 해당 로직은 …

PR: publish-main searchbar 수정했습니다.

---

src/libs/axios/base/products.js

- 상품 등록
- 메인 상품 목록 조회
- 물품 검색
- 상품 상세
- 관심 상품 등록/해제
- 물품 수정
- 물품 삭제
- 물품 판매 완료
- 물품 시세 검색
- 최근 본 상품 목록 조회
- 최근 본 상품 추가
- 최근 본 상품 삭제
> *함수컨벤션
> 요청종류 / 요청주소 / 정보 / By parameter
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: Product API 생성했습니다.

---

src/components/commons/button.jsx
src/components/detail-product/detail-image.jsx
src/components/detail-product/detail-info.jsx
src/components/detail-product/index.js
src/components/detail-product/item-summary.jsx
src/components/detail-product/seller-banner.jsx
src/components/detail-product/tag-product/index.js
src/components/detail-product/tag-product/tag-product-chart.jsx
src/components/detail-product/tag-product/tag-products.jsx
src/libs/react-router-dom/router.jsx
src/pages/detail-product-page.jsx

[PR/PD-49: detail-product 페이지 퍼블리싱 완료했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/64)부분을 이어서 작성합니다
- [design: detialProduct,Info컴포넌트 생성](0f8f97374ed092c83fc19b7ff04a864b64754b74)
- 배너를 중심으로 기준을 나눠서 컴포넌트를 작성했습니다
- 디테일 이미지부분과 설명 부분을 나눠서 작성햇습니다
- 채팅하기 와 공유하기 및 찜하트 부분 기능 추가 들어가야됩니다
- product부분 선택할시 border색변경가능하게 했습니
</div>
- [design : banner 컴포넌트 생성](58a5db57194504c916312cb2bad0e856b829c294)
-  배너안의 main숫자 api받아오면기능추가로  문자열 함수로 변경해주면됩니다 
- [desgin: TagProducts 컴포넌트 작성했습니다](4261bbce5136e3a10d93f850fc85b667ad6a7952)
- TagChart 가 api추가되면서 생성될시 사용할컴포넌트도  생성은 해놨습니다 그전까지는 직접 detail-product-page에 사용되고 그후에는 TagData에서 사용될예정입니다
- 여기까지가 전 pr 입니다
----
- 사이즈 조절및 media 사이즈 다 추가했습니다
--마지막 2개 부분은 이미 컨펌된 부분이라 따로영상으론  올리진않았습니다
<br/>
<br/>
-   [x] PR 제목 …

PR/PD-49: detail-product 페이지 퍼블리싱 완료했습니다.(대체)

---

src/components/commons/eight-product-grid.jsx
src/constants/query-key.js
src/libs/react-query/products.js
src/pages/product-list-page.jsx
src/utils/index.js
src/utils/regional-word-extractor.js

- [feat: 행정구역 이름 추출 함수 작성](https://github.com/PurpleDynamics/PEA_Project/commit/f88e72b3690c6d4cdcf6b5bb20285a761ad6e04f)
- 서버에서 넘어온 주소 중, 특정 행정구역 정보를 추출하는 함수 작성했습니다.
- `extractRegionalUnitDong` : '-동' 단위 주소만 출력
-  `extractRegionalUnitGu` : '-구' 단위 주소만 출력
- [feat: getProduct(), react-query 활용 query 최적화](https://github.com/PurpleDynamics/PEA_Project/commit/2c6903487bfc850f9c45d8a5f1425b0fedd270b9)
- react-query 사용해서, `useProductList` 작성했습니다.
- '중고'.'무료' 카테고리의 각각 8개 상품 정보를 받을 수 있는 `getProduct` 함수와 관련하여 query 최적화 진행했습니다.
- [feat: product-list-page 데이터 패칭](https://github.com/PurpleDynamics/PEA_Project/commit/50d72db495d17c8f4aa5ee7be5fb75c68e9ecb57)
- <img width="735" alt="스크린샷 2024-03-03 오후 11 47 06" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/1b52178b-fb29-489b …

PR/PD-85: ProductList 데이터 패칭 작업했습니다.
